### ISSUE TITLE
Moab storage root lookup: start with most recent root?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/moab-versioning#124]
@blalbrit @LynnMcRae @julianmorley  In working with the preservation robot code, I am struck by having 3 or 4 sequential robots that each do a lookup for a Moab.   But if we know which storage root has (or will have) the Moab, then the lookup is presumably much cheaper ...

Because moab-versioning gem is designed to look for the object in every storage root, sequentially:
https://github.com/sul-dlss/moab-versioning/blob/master/lib/moab/storage_repository.rb#L69-L93

But if we already know which storage root (from the first time we look it up for preservation robots), then we can potentially save a bunch of needless searching.

So questions:

#### storage root lookup order

* what do you think about looking for the moab in the newest root first?   That is 15, 14, 13 ...   rather than (1), 2, 3  as the lookup order?    I am supposing that the newest objects get the most lookups.
    * it would be really cool to have actual data on which roots are accessed the most via Moab code rather than guessing.

#### minimal state info across robot instances or within suite

* what do you think about retaining a moab -> storage root mapping (oh wait - that's the preservation catalog) for the preservation robots?
    * where else do we instantiate moabs / where else might benefit from such caching?  https://github.com/sul-dlss/moab-versioning/network/dependents might be a way to find out this info.
    * the existing preservation robots try to cache apo ids to avoid extra lookups in the verify-agreement (soon to be verify-apo) robot step.   It's a well intended thought ... I'm just not sure if the way it was done works.   I will be performing an experiment to find out.

**Comment by julianmorley** [comment]
I definitely have some thoughts on this, but they’ll have to wait until next week.

--
Julian M. Morley
Technology Infrastructure Manager
Digital Library Systems & Services
Stanford University Libraries
________________________________

**Comment by julianmorley** [comment]
OK, I'm back. What's the actual cost of the lookup? My crappy bash script returns a location in < half a second, which is fine for it's particular usecase. Otherwise I fear we're just spending cycles optimizing something that can be optimized, but doesn't need to be.

Now, given how the robots work, the easiest way to do a lookup table for moab would be to write that info to a text file on the local processing node. That'll result in the file being cached in the system's page buffer, and give us a non-network-access path for lookups. Fall back to the old discovery code only if the Moab's not found in the lookup file.

**Comment by LynnMcRae** [comment]
I thought we were recording the storage root in the catalog for this very purpose. Seems kinda silly to do so and not use it, delta any local caching of answers to minimize even the DB lookup.

**Comment by atz** [comment]
Whether in the DB or not doesn't matter because we still use `Moab::StorageRepository` to derive the canonical path to the object and *it* still goes through all the storage roots.  This isn't a question about an app.  It is about optimizing `Moab::Versioning` behavior, which has no knowledge of any DB.  

Writing pointers to additional text files is a non-starter, imo.  Not scalable, precludes use on systems that have read-only mounts of storage roots, huge conversion cost.  The write contention on singular drive vs. parallelized robots is a dealbreaker in itself.

The MV code is used intensively throughout PreservationCatalog and elsewhere, and some logic here would conceivably give a modest return.

**Comment by ndushay** [comment]
I'm closing this because we have a MUCH smaller number of storage roots now.
